---(1) HOW MANY TRANSACTION WERE MADE

SELECT COUNT(*) AS TOT_TRANS 
FROM PAYMENT;

---(2)TOTAL REVENUE GENERATED BY THE COMPANY

SELECT SUM(AMOUNT) AS TOT_REVENE 
FROM PAYMENT;

---(3)TOP 10 CUSTOMERS THAT MADE THE HIGHEST NUMBERS OF TRANSACTIONS

SELECT customer.customer_id, customer.first_name, customer.last_name, COUNT(payment.amount) as No_of_Trans 
FROM CUSTOMER
LEFT JOIN PAYMENT
ON customer.customer_id=payment.customer_id
GROUP BY customer.customer_id, customer.first_name, customer.last_name
ORDER BY COUNT(amount) DESC
LIMIT 10;

---(4)TOP 10 BEST PATRONIZING CUSTOMERS THAT MADE MAXIMUM TRANSACTIONS PAYMENTS

SELECT customer.customer_id, customer.first_name, customer.last_name, SUM(payment.amount) as Amt_paid 
FROM CUSTOMER
LEFT JOIN PAYMENT
ON customer.customer_id=payment.customer_id
GROUP BY customer.customer_id, customer.first_name, customer.last_name
ORDER BY SUM(amount) DESC
LIMIT 10;

---(5)RETURN THE CUSTOMER_IDs OF CUSTOMERS WHO HAVE SPENT ATLEAST $110 WITH THE STAFF MEMBER WHO HAS AN ID OF 2

SELECT customer_id,SUM(Amount),staff_id
FROM PAYMENT
GROUP BY payment.customer_id,payment.staff_id
HAVING SUM(Amount)>=110 AND staff_id= 2
ORDER BY customer_id ASC;

---(6)RETRIEVE THE NAMES OF THOSE DISTINCT DISTRICTS

SELECT DISTINCT (district) 
FROM ADDRESS; 

---(7)HOW MANY UNIQUE DISTRICTS DID ALL THE CUSTOMERS FROM

SELECT COUNT (DISTINCT district) AS TOT_Dis 
FROM ADDRESS;

---(8)TOTAL NUMBER OF CUSTOMERS FROM EACH UNIQUE DISTRICT

SELECT  district ,COUNT(customer_id) AS Tot_Cus 
FROM customer
INNER JOIN address 
ON customer.address_id=address.address_id
GROUP BY district
ORDER BY Tot_Cus DESC;

